apiVersion: v1
kind: Pod
metadata:
  name: runtime
  labels:
    app: runtime
spec:
  containers:
    - name: runtime
      image: amirhossein21/runtime:latest
      ports:
        - containerPort: 80